spring:
    datasource:
        #username: postgres
        #url: jdbc:postgresql://localhost:5432/user-task
        #password: secret
        driverClassName: org.h2.Driver
        username: sa
        password:
        h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
                trace: false
            path: /h2-console
            allowed-origins: "*"
    jpa:
        #database-platform: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    #sql:
        #init:
            #platform: postgres
feign:
    name: jplaceholder
    base-url: "https://jsonplaceholder.typicode.com"
    photo-resource: "/photos"
server:
    port: 8080
    servlet:
        context-path: /example
        session:
            timeout: 21600s
   